import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { projectDetail, recordDetails } from '../../api-server/src/lib/demo-data.ts';

const SITE_URL = 'https://is-harry-tired.replit.app';
const SITE_ID = `${SITE_URL}/#website`;
const PUBLISHER_ID = `${SITE_URL}/#publisher`;
const artifactDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputDir = path.join(artifactDir, 'dist/public');
const template = await readFile(path.join(outputDir, 'index.html'), 'utf8');
type StaticPage = { route: string; title: string; description: string; eyebrow: string; heading: string; copy: string; links: Array<{ href: string; label: string }>; indexable?: boolean; structuredData?: Record<string, unknown> };
const escapeHtml = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const formatDate = (date: Date) => new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(date);
const absoluteUrl = (route: string) => new URL(route, `${SITE_URL}/`).toString();
const momentLinks = projectDetail.moments.map((moment) => ({ href: `/projects/${projectDetail.slug}/moments/${moment.slug}/comparison`, label: `${moment.name} comparison` }));
const recordLinks = recordDetails.map((record) => ({ href: `/projects/${projectDetail.slug}/records/${record.slug}`, label: `${formatDate(record.date)} — ${record.venue}` }));

const pages: StaticPage[] = [
  { route: '/', title: 'Field Notes · Open Performance Review', description: 'An open-source, local-first tool for comparing repeatable public performance moments without making claims about an artist’s private condition.', eyebrow: 'Open-source field record / local-first', heading: 'Compare a performance without pretending to know a person.', copy: 'Choose a project, hold the same moments steady across show nights, and publish what public records show—plus where the evidence stops. Roll your own with the runnable source on GitHub.', links: [{ href: '/projects', label: 'Explore the example project' }, { href: '/import', label: 'Import a record file' }, { href: '/about', label: 'Read the method and limits' }, { href: 'https://github.com/jratlee/open-performance-review', label: 'Download the source on GitHub' }] },
  { route: '/projects', title: 'Example Projects · Field Notes', description: 'Browse artist-agnostic performance review projects with visible sources, provenance, coverage, and cautious comparison results.', eyebrow: 'Available projects / illustrative example', heading: 'Projects.', copy: 'Each project defines an artist, a show run, repeatable moments, linked sources, and evidence limits.', links: [{ href: `/projects/${projectDetail.slug}`, label: `Open ${projectDetail.name}` }, ...momentLinks, { href: '/import', label: 'Import a local project' }], structuredData: { '@context': 'https://schema.org', '@type': 'ItemList', '@id': `${absoluteUrl('/projects')}#projects`, url: absoluteUrl('/projects'), name: 'Open performance review projects', numberOfItems: 1, itemListElement: [{ '@type': 'ListItem', position: 1, url: absoluteUrl(`/projects/${projectDetail.slug}`), name: projectDetail.name }] } },
  { route: '/about', title: 'Method, Format, and Limits · Field Notes', description: 'Learn the open performance review record format, comparison rule, source-use expectations, and evidence limits.', eyebrow: 'Method / format / limits', heading: 'Make a review another community can run.', copy: 'Field Notes keeps a repeatable moment, the source that supports it, and the limits of the comparison in the same record.', links: [{ href: '/', label: 'Return to field notes' }, { href: '/import', label: 'Try the import format' }] },
  { route: '/import', title: 'Import Performance Records · Field Notes', description: 'Validate a local JSON or CSV performance review file in the browser without uploading or hosting source media.', eyebrow: 'Local browser import / untrusted input', heading: 'Bring a record you can inspect.', copy: 'Validate a small JSON or CSV project in your browser before comparing it. The file is not uploaded, saved, or rendered as media.', links: [{ href: '/about', label: 'Read the record format' }, { href: '/projects', label: 'Browse the example project' }] },
  { route: `/projects/${projectDetail.slug}`, title: `${projectDetail.name} · Field Notes`, description: projectDetail.description, eyebrow: `${projectDetail.status} project / ${projectDetail.artist.name}`, heading: projectDetail.name, copy: projectDetail.sourcePolicy, links: [...recordLinks, ...momentLinks, { href: '/about', label: 'Read the project method' }], structuredData: { '@context': 'https://schema.org', '@type': 'CreativeWork', '@id': `${absoluteUrl(`/projects/${projectDetail.slug}`)}#project`, url: absoluteUrl(`/projects/${projectDetail.slug}`), name: projectDetail.name, description: projectDetail.description, isPartOf: { '@id': SITE_ID }, publisher: { '@id': PUBLISHER_ID } } },
  ...recordDetails.map((record): StaticPage => ({ route: `/projects/${projectDetail.slug}/records/${record.slug}`, title: `${formatDate(record.date)} Performance Record · Field Notes`, description: record.summary ?? record.coverageNote, eyebrow: `${formatDate(record.date)} / performance record`, heading: record.venue, copy: record.summary ?? record.coverageNote, links: [{ href: `/projects/${projectDetail.slug}`, label: 'Browse project records' }, ...momentLinks, { href: '/about', label: 'Read the comparison method' }], structuredData: { '@context': 'https://schema.org', '@type': 'CreativeWork', '@id': `${absoluteUrl(`/projects/${projectDetail.slug}/records/${record.slug}`)}#record`, url: absoluteUrl(`/projects/${projectDetail.slug}/records/${record.slug}`), name: `${record.venue} performance record`, description: record.summary ?? record.coverageNote, isPartOf: { '@id': `${absoluteUrl(`/projects/${projectDetail.slug}`)}#project` }, citation: record.moments.flatMap((moment) => moment.sources.map((source) => source.url)) } })),
  ...projectDetail.moments.map((moment): StaticPage => ({ route: `/projects/${projectDetail.slug}/moments/${moment.slug}/comparison`, title: `${moment.name} comparison · Field Notes`, description: 'Compare one repeatable public performance moment across records with visible source and baseline limits.', eyebrow: 'Same moment / project comparison', heading: moment.name, copy: 'Compare the same defined segment across records. If the baseline is weak, the result is not enough to tell.', links: [{ href: `/projects/${projectDetail.slug}`, label: 'Browse project records' }, { href: '/about', label: 'Read the comparison method' }], structuredData: { '@context': 'https://schema.org', '@type': 'CollectionPage', '@id': `${absoluteUrl(`/projects/${projectDetail.slug}/moments/${moment.slug}/comparison`)}#comparison`, url: absoluteUrl(`/projects/${projectDetail.slug}/moments/${moment.slug}/comparison`), name: `${moment.name} comparison`, description: moment.description, isPartOf: { '@id': `${absoluteUrl(`/projects/${projectDetail.slug}`)}#project` }, publisher: { '@id': PUBLISHER_ID } } })),
];

function replaceMeta(page: StaticPage) {
  const canonicalUrl = `${SITE_URL}${page.route}`;
  const robots = page.indexable === false ? 'noindex, nofollow' : 'index, follow';
  const structuredData = page.structuredData ? `    <script type="application/ld+json">${JSON.stringify(page.structuredData).replaceAll('<', '\\u003c')}</script>\n` : '';
  return template.replace(/<title>.*?<\/title>/s, `<title>${escapeHtml(page.title)}</title>`).replace(/<meta name="description" content=".*?" \/>/s, `<meta name="description" content="${escapeHtml(page.description)}" />`).replace(/<meta name="robots" content=".*?" \/>/s, `<meta name="robots" content="${robots}" />`).replace(/<meta property="og:title" content=".*?" \/>/s, `<meta property="og:title" content="${escapeHtml(page.title)}" />`).replace(/<meta property="og:description" content=".*?" \/>/s, `<meta property="og:description" content="${escapeHtml(page.description)}" />`).replace(/<meta property="og:url" content=".*?" \/>/s, `<meta property="og:url" content="${canonicalUrl}" />`).replace(/<meta name="twitter:title" content=".*?" \/>/s, `<meta name="twitter:title" content="${escapeHtml(page.title)}" />`).replace(/<meta name="twitter:description" content=".*?" \/>/s, `<meta name="twitter:description" content="${escapeHtml(page.description)}" />`).replace('</head>', `${structuredData}  </head>`);
}

function fallbackMarkup(page: StaticPage) {
  const links = page.links.map(({ href, label }) => `<li><a href="${href}">${escapeHtml(label)}</a></li>`).join('');
  return `<div id="root"><header><nav aria-label="Main navigation"><a href="/">Field Notes</a><a href="/projects">Example projects</a><a href="/about">Method</a></nav></header><main><article><p>${escapeHtml(page.eyebrow)}</p><h1>${escapeHtml(page.heading)}</h1><p>${escapeHtml(page.copy)}</p><nav aria-label="Related pages"><ul>${links}</ul></nav></article></main><footer><p>Observable public performance records, not a diagnosis of anyone’s private condition.</p></footer></div>`;
}

for (const page of pages) {
  const html = replaceMeta(page).replace('<div id="root"></div>', fallbackMarkup(page));
  const file = page.route === '/' ? path.join(outputDir, 'index.html') : path.join(outputDir, page.route.slice(1), 'index.html');
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, html);
}
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.filter((page) => page.indexable !== false).map((page) => `  <url><loc>${SITE_URL}${page.route}</loc><changefreq>${page.route === '/' ? 'weekly' : 'monthly'}</changefreq><priority>${page.route === '/' ? '1.0' : '0.7'}</priority></url>`).join('\n')}\n</urlset>\n`;
await writeFile(path.join(outputDir, 'sitemap.xml'), sitemap);
await writeFile(path.join(outputDir, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${SITE_URL}/sitemap.xml\n`);
console.log(`Generated ${pages.length} static route documents and ${pages.length} sitemap entries.`);